"""EMBEDHUNT AI — Application Constants"""
MAX_RESUME_SIZE_BYTES = 5 * 1024 * 1024  # 5MB
ALLOWED_RESUME_EXTENSIONS = {".pdf", ".docx", ".txt"}
MIN_RESUME_TEXT_LENGTH = 50
MAX_RESUME_TEXT_LENGTH = 100_000

AUTO_APPLY_SCORE_THRESHOLD = 85
SHOW_JOB_SCORE_THRESHOLD = 40
DEFAULT_MIN_SALARY_LPA = 15.0

MAX_FAILED_LOGIN_ATTEMPTS = 5
LOCKOUT_DURATION_MINUTES = 30
