"""initial schema

Revision ID: 8a59bc768e7f
Revises: 
Create Date: 2026-06-22 15:43:45.772465
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '8a59bc768e7f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applications',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=200), nullable=False),
    sa.Column('resume_id', sa.String(length=36), nullable=False),
    sa.Column('job_title', sa.String(length=300), nullable=False),
    sa.Column('company_name', sa.String(length=200), nullable=False),
    sa.Column('company_tier', sa.String(length=50), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=False),
    sa.Column('apply_url', sa.String(length=1000), nullable=False),
    sa.Column('source_portal', sa.String(length=100), nullable=False),
    sa.Column('salary_min_lpa', sa.Float(), nullable=True),
    sa.Column('salary_max_lpa', sa.Float(), nullable=True),
    sa.Column('match_score', sa.Integer(), nullable=False),
    sa.Column('matched_skills', sa.Text(), nullable=False),
    sa.Column('missing_skills', sa.Text(), nullable=False),
    sa.Column('ai_explanation', sa.Text(), nullable=False),
    sa.Column('resume_version_name', sa.String(length=200), nullable=False),
    sa.Column('cover_letter', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('APPROVED', 'QUEUED', 'APPLYING', 'SUBMITTED', 'FAILED', 'WITHDRAWN', 'RESPONDED', name='app_status_enum'), nullable=False),
    sa.Column('outcome', sa.Enum('PENDING', 'SHORTLISTED', 'INTERVIEW', 'OFFER', 'REJECTED', 'GHOSTED', name='app_outcome_enum'), nullable=False),
    sa.Column('approved_at', sa.String(length=50), nullable=True),
    sa.Column('submitted_at', sa.String(length=50), nullable=True),
    sa.Column('responded_at', sa.String(length=50), nullable=True),
    sa.Column('apply_attempt_count', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('confirmation_number', sa.String(length=200), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_applications_job_id'), 'applications', ['job_id'], unique=False)
    op.create_index(op.f('ix_applications_user_id'), 'applications', ['user_id'], unique=False)
    op.create_table('candidate_profiles',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('headline', sa.String(length=300), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('total_experience_years', sa.Float(), nullable=False),
    sa.Column('current_role', sa.String(length=200), nullable=True),
    sa.Column('current_company', sa.String(length=200), nullable=True),
    sa.Column('skills_json', sa.Text(), nullable=True),
    sa.Column('profile_json', sa.Text(), nullable=True),
    sa.Column('embedded_domain_score', sa.Integer(), nullable=False),
    sa.Column('profile_score', sa.Integer(), nullable=False),
    sa.Column('is_actively_looking', sa.Boolean(), nullable=False),
    sa.Column('preferred_locations', sa.Text(), nullable=True),
    sa.Column('min_salary_lpa', sa.Float(), nullable=False),
    sa.Column('notice_period_days', sa.Integer(), nullable=False),
    sa.Column('highest_degree', sa.String(length=100), nullable=True),
    sa.Column('field_of_study', sa.String(length=200), nullable=True),
    sa.Column('graduation_year', sa.Integer(), nullable=True),
    sa.Column('total_recommendations', sa.Integer(), nullable=False),
    sa.Column('total_applications', sa.Integer(), nullable=False),
    sa.Column('interview_rate', sa.Float(), nullable=False),
    sa.Column('offer_rate', sa.Float(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidate_profiles_user_id'), 'candidate_profiles', ['user_id'], unique=True)
    op.create_table('companies',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('tier', sa.String(length=50), nullable=False),
    sa.Column('careers_url', sa.String(length=500), nullable=True),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('company_size', sa.String(length=50), nullable=True),
    sa.Column('headquarters', sa.String(length=200), nullable=True),
    sa.Column('tech_stack', sa.Text(), nullable=True),
    sa.Column('embedded_domains', sa.Text(), nullable=True),
    sa.Column('avg_salary_min_lpa', sa.Float(), nullable=True),
    sa.Column('avg_salary_max_lpa', sa.Float(), nullable=True),
    sa.Column('interview_difficulty', sa.String(length=20), nullable=False),
    sa.Column('priority_score', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('call_rate', sa.Float(), nullable=False),
    sa.Column('offer_rate', sa.Float(), nullable=False),
    sa.Column('total_applications_sent', sa.Integer(), nullable=False),
    sa.Column('total_interviews', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_companies_name'), 'companies', ['name'], unique=False)
    op.create_table('interview_sessions',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('job_title', sa.String(length=300), nullable=False),
    sa.Column('company', sa.String(length=200), nullable=True),
    sa.Column('application_id', sa.String(length=36), nullable=True),
    sa.Column('readiness_score', sa.Integer(), nullable=False),
    sa.Column('questions_json', sa.Text(), nullable=True),
    sa.Column('coding_topics', sa.Text(), nullable=True),
    sa.Column('checklist_json', sa.Text(), nullable=True),
    sa.Column('estimated_prep_days', sa.Integer(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interview_sessions_user_id'), 'interview_sessions', ['user_id'], unique=False)
    op.create_table('job_recommendations',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=200), nullable=False),
    sa.Column('job_title', sa.String(length=300), nullable=False),
    sa.Column('company_name', sa.String(length=200), nullable=False),
    sa.Column('company_tier', sa.String(length=50), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=False),
    sa.Column('source_portal', sa.String(length=100), nullable=False),
    sa.Column('source_url', sa.String(length=1000), nullable=False),
    sa.Column('apply_url', sa.String(length=1000), nullable=True),
    sa.Column('salary_min_lpa', sa.Float(), nullable=True),
    sa.Column('salary_max_lpa', sa.Float(), nullable=True),
    sa.Column('meets_salary_filter', sa.Boolean(), nullable=False),
    sa.Column('match_score', sa.Integer(), nullable=False),
    sa.Column('match_tier', sa.Enum('AUTO_APPLY', 'STRONG', 'GOOD', 'PARTIAL', name='match_tier_enum'), nullable=False),
    sa.Column('is_auto_apply_candidate', sa.Boolean(), nullable=False),
    sa.Column('matched_skills', sa.Text(), nullable=False),
    sa.Column('missing_skills', sa.Text(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('gap_analysis_json', sa.Text(), nullable=True),
    sa.Column('is_dismissed', sa.Boolean(), nullable=False),
    sa.Column('is_saved', sa.Boolean(), nullable=False),
    sa.Column('scan_run_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_recommendations_user_id'), 'job_recommendations', ['user_id'], unique=False)
    op.create_table('learning_roadmaps',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('target_job_title', sa.String(length=300), nullable=False),
    sa.Column('target_company', sa.String(length=200), nullable=True),
    sa.Column('score_before', sa.Integer(), nullable=False),
    sa.Column('score_after_estimated', sa.Integer(), nullable=False),
    sa.Column('total_gap_skills', sa.Integer(), nullable=False),
    sa.Column('estimated_weeks', sa.Integer(), nullable=False),
    sa.Column('tasks_json', sa.Text(), nullable=True),
    sa.Column('completed_skills', sa.Text(), nullable=True),
    sa.Column('progress_pct', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learning_roadmaps_user_id'), 'learning_roadmaps', ['user_id'], unique=False)
    op.create_table('notifications',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.Enum('NEW_JOB_MATCH', 'APPLICATION_UPDATE', 'PROFILE_TIP', 'INTERVIEW_REMINDER', 'WEEKLY_SUMMARY', 'SYSTEM', name='notif_type_enum'), nullable=False),
    sa.Column('channel', sa.Enum('IN_APP', 'EMAIL', 'PUSH', name='notif_channel_enum'), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('action_url', sa.String(length=500), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('is_sent', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('resumes',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('file_url', sa.String(length=1000), nullable=False),
    sa.Column('file_name', sa.String(length=300), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('file_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('UPLOADED', 'PARSING', 'PARSED', 'PARSE_FAILED', 'EMBEDDING_READY', name='resume_status_enum'), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('parsed_skills', sa.Text(), nullable=True),
    sa.Column('parsed_experience', sa.Text(), nullable=True),
    sa.Column('parsed_education', sa.Text(), nullable=True),
    sa.Column('parsed_projects', sa.Text(), nullable=True),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('skill_score', sa.Float(), nullable=True),
    sa.Column('embedding_id', sa.String(length=100), nullable=True),
    sa.Column('is_embedding_ready', sa.Boolean(), nullable=False),
    sa.Column('is_auto_generated', sa.Boolean(), nullable=False),
    sa.Column('generated_for_job_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resumes_user_id'), 'resumes', ['user_id'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('linkedin_url', sa.String(length=500), nullable=True),
    sa.Column('github_url', sa.String(length=500), nullable=True),
    sa.Column('role', sa.Enum('CANDIDATE', 'RECRUITER', 'COMPANY_ADMIN', 'PLATFORM_ADMIN', name='user_role_enum'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('is_premium', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.String(length=50), nullable=True),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.String(length=50), nullable=True),
    sa.Column('email_verify_token', sa.String(length=500), nullable=True),
    sa.Column('password_reset_token', sa.String(length=500), nullable=True),
    sa.Column('min_salary_lpa', sa.Float(), nullable=False),
    sa.Column('target_salary_lpa', sa.Float(), nullable=False),
    sa.Column('preferred_locations', sa.String(length=500), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_resumes_user_id'), table_name='resumes')
    op.drop_table('resumes')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_learning_roadmaps_user_id'), table_name='learning_roadmaps')
    op.drop_table('learning_roadmaps')
    op.drop_index(op.f('ix_job_recommendations_user_id'), table_name='job_recommendations')
    op.drop_table('job_recommendations')
    op.drop_index(op.f('ix_interview_sessions_user_id'), table_name='interview_sessions')
    op.drop_table('interview_sessions')
    op.drop_index(op.f('ix_companies_name'), table_name='companies')
    op.drop_table('companies')
    op.drop_index(op.f('ix_candidate_profiles_user_id'), table_name='candidate_profiles')
    op.drop_table('candidate_profiles')
    op.drop_index(op.f('ix_applications_user_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_job_id'), table_name='applications')
    op.drop_table('applications')
    # ### end Alembic commands ###
